import type { Skilltype } from "@/types/skill";
import {
  FaHtml5,
  FaReact,
  FaPython,
  FaJava,
  FaJsSquare,
  FaCss3Alt,
  FaLinux,
} from "react-icons/fa";
import { IoTerminal } from "react-icons/io5";
import {
  SiTypescript,
  SiNextdotjs,
  SiTailwindcss,
  SiPrisma,
  SiDocker,
  SiMongodb,
  SiAstro,
  SiNodedotjs,
  SiExpress,
  SiUnity,
  SiPostgresql,
  SiDjango,
  SiGnubash,
} from "react-icons/si";
import { TbBrandCSharp } from "react-icons/tb";

export const skillData: Skilltype[] = [
  {
    id: 0,
    name: "HTML",
    description: "HTML builds the content of a website.",
    icon: <FaHtml5 />,
    progress: 98,
    tags: ["language", "web"],
  },
  {
    id: 1,
    name: "CSS",
    progress: 95,
    description: "CSS styles the looks and layouts of a website.",
    tags: ["language", "web"],
    icon: <FaCss3Alt />,
  },
  {
    id: 2,
    name: "JavaScript",
    progress: 90,
    description: "JavaScript makes a website interactive.",
    tags: ["language", "web"],
    icon: <FaJsSquare />,
  },
  {
    id: 16,
    name: "TypeScript",
    progress: 70,
    description: "JavaScript but way more annoying and with types.",
    tags: ["language", "web"],
    icon: <SiTypescript />,
  },
  {
    id: 3,
    name: "React",
    progress: 80,
    description: "The most popular JS component-based library.",
    tags: ["language", "web"],
    icon: <FaReact />,
  },
  {
    id: 4,
    name: "Next.js",
    progress: 65,
    description: "React but with better routing and backend.",
    tags: ["language", "web"],
    icon: <SiNextdotjs />,
  },
  {
    id: 5,
    name: "Tailwind",
    progress: 75,
    description: "Framework that writes CSS with HTML utility classes.",
    tags: ["language", "web"],
    icon: <SiTailwindcss />,
  },
  {
    id: 17,
    name: "Prisma",
    progress: 35,
    description: "TypeScript-based object-relational mapping library.",
    tags: ["web", "tool"],
    icon: <SiPrisma />,
  },
  {
    id: 18,
    name: "PostgreSQL",
    progress: 30,
    description: "Powerful, complex, and popular SQL database.",
    tags: ["web", "tool"],
    icon: <SiPostgresql />,
  },
  {
    id: 19,
    name: "Docker",
    progress: 40,
    description: "Containerizes app dev environments.",
    tags: ["web", "tool"],
    icon: <SiDocker />,
  },
  {
    id: 22,
    name: "CLI Tools",
    progress: 40,
    description: "Using command line tools like Git, npm and Docker.",
    tags: ["web", "tool"],
    icon: <IoTerminal />,
  },
  {
    id: 6,
    name: "MongoDB",
    progress: 60,
    description: "Beginner friendly database for full stack apps.",
    tags: ["language", "web"],
    icon: <SiMongodb />,
  },
  {
    id: 7,
    name: "Astro",
    progress: 30,
    description: "Static framework for content-driven websites.",
    tags: ["language", "web"],
    icon: <SiAstro />,
  },
  {
    id: 8,
    name: "Node",
    progress: 50,
    description: "JavaScript runtime that runs JS anywhere.",
    tags: ["language", "web"],
    icon: <SiNodedotjs />,
  },
  {
    id: 9,
    name: "Express",
    progress: 50,
    description: "Framework for Node.js that simplifies a lot of things.",
    tags: ["language", "web"],
    icon: <SiExpress />,
  },
  {
    id: 10,
    name: "Python",
    progress: 40,
    description: "Python is a powerful and versatile language.",
    tags: ["language"],
    icon: <FaPython />,
  },
  {
    id: 20,
    name: "Django",
    progress: 30,
    description: "Fullstack/backend Python web framework.",
    tags: ["web", "language"],
    icon: <SiDjango />,
  },
  {
    id: 11,
    name: "Java",
    progress: 40,
    description: "Popular language that's used almost everywhere.",
    tags: ["language"],
    icon: <FaJava />,
  },
  {
    id: 12,
    name: "Unity",
    progress: 40,
    description: "The most used game engine to make games.",
    tags: ["tool"],
    icon: <SiUnity />,
  },
  {
    id: 13,
    name: "C#",
    progress: 15,
    description: "A versatile programming language used by Unity.",
    tags: ["language"],
    icon: <TbBrandCSharp />,
  },
  {
    id: 14,
    name: "Linux",
    progress: 40,
    description: "Setting up/working with OS, terminals, and bash.",
    tags: ["tool"],
    icon: <FaLinux />,
  },
  {
    id: 21,
    name: "Bash",
    progress: 25,
    description: "Writing scripts with bash commands and syntax.",
    tags: ["tool", "language"],
    icon: <SiGnubash />,
  },
];
